apiVersion: skaffold/v1beta4
kind: Config
build:
  local:
    push: false
  artifacts:
    - image: local/continous-development
      jibGradle: {}
deploy:
  kubectl:
    manifests:
      - skaffold/*.yaml