apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo-app
  template:
    metadata:
      labels:
        app: demo-app
    spec:
      containers:
        - name: demo-app-pod
          image: local/continous-development
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 55000
---
apiVersion: v1
kind: Service
metadata:
  name: demo-app-service
spec:
  type: LoadBalancer
  ports:
    - port: 8080
      targetPort: 55000
      protocol: TCP
      name: http
  selector:
    app: demo-app

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: localstack
spec:
  # using the selector, we will expose the running deployments
  # this is how Kubernetes knows, that a given service belongs to a deployment
  selector:
    matchLabels:
      app: localstack
  replicas: 1
  template:
    metadata:
      labels:
        app: localstack
    spec:
      containers:
        - name: localstack
          image: localstack/localstack:0.10.8
          ports:
            # exposing s3
            - containerPort: 31002
            # exposing dynamodb
            - containerPort: 31001
            # exposing sqs
            - containerPort: 31000
            # exposing the localstack ui
            - containerPort: 32000
          env:
            # with the SERVICES environment variable, you can tell LocalStack
            # what services to expose on what port
            - name: SERVICES
              value: "sqs:31000,dynamodb:31001,s3:31002"
            - name: PORT_WEB_UI
              value: "32000"
---
apiVersion: v1
kind: Service
metadata:
  name: localstack
spec:
  # selector tells Kubernetes what Deployment this Service
  # belongs to
  selector:
    app: localstack
  ports:
    - port: 32000
      protocol: TCP
      name: ui
      nodePort: 32000
    - port: 31002
      protocol: TCP
      name: s3
      nodePort: 31002
    - port: 31001
      protocol: TCP
      name: dynamodb
      nodePort: 31001
    - port: 31000
      protocol: TCP
      name: sqs
      nodePort: 31000
  type: LoadBalancer
